## Going from list to Numpy arrays


In [1]:
w1,w2,w3 = 0.3,0.2,0.5

In [2]:
kanto_temp = 78
kanto_rainfall = 56
kanto_humidity = 34

In [3]:
kanto_yield_apples = kanto_temp*w1+kanto_rainfall*w2+kanto_humidity*w3
kanto_yield_apples

51.6

In [4]:
print("The expected yield of apple in kanto is{} tons",kanto_yield_apples)

The expected yield of apple in kanto is{} tons 51.6


In [5]:
kanto = [78,56,34]
niraj = [90,88,23]
sonu = [89,343, 45]
kajal = [67,78,45]


In [6]:
weights = [w1,w2,w3]

In [7]:
for itam in zip(kanto, weights):
    print(itam)

(78, 0.3)
(56, 0.2)
(34, 0.5)


In [8]:
def crop_yield(region, weights):
    result = 0
    for x,w in zip (region, weights):
        result += x*w
        return result

In [9]:
 crop_yield(kanto, weights)

23.4

In [10]:
 crop_yield(niraj, weights)

27.0

In [11]:
 crop_yield(sonu, weights)

26.7

In [12]:
 crop_yield(kajal, weights)

20.099999999999998

In [13]:
import numpy as np

In [14]:
kanto = np.array([78,56,34])

In [15]:
kanto

array([78, 56, 34])

In [16]:
weights = np.array([w1,w2,w3])

In [17]:
weights

array([0.3, 0.2, 0.5])

In [18]:
type(kanto)

numpy.ndarray

In [19]:
type(weights)

numpy.ndarray

In [20]:
weights[0]

0.3

In [21]:
kanto[2]

34

# Operation on Numpy arrays
We can now compute the dot product of the two vectors using the np.dot function

In [22]:
np.dot(kanto,weights)

51.6

In [23]:
(kanto*weights).sum()

51.6

In [24]:
arr1 = np.array([1,2,34,4])
arr2 = np.array([4,5,6,7])

In [25]:
arr1*arr2

array([  4,  10, 204,  28])

In [26]:
arr2.sum()

22

## Benefits of usin /Numpy arrays

**. Ease of use:**, You can write.....

**. performancer:**,crop yild

In [27]:
arr1 = list(range(10000))
arr2 = list(range(10000,20000))
#numpy arrays 
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [28]:
%%time
result = 0 
for x1, x2 in zip (arr1,arr2):
    result += x1*x2
    result

Wall time: 0 ns


In [29]:
%%time
np.dot (arr1_np, arr2_np)

Wall time: 3.55 ms


9679576

## Multi-dimension Numpy arrays

In [30]:
climate_data = np.array([[78,56,45],
                        [90,88,65],
                        [87,145,23],
                        [110,43,56]])

In [31]:
climate_data

array([[ 78,  56,  45],
       [ 90,  88,  65],
       [ 87, 145,  23],
       [110,  43,  56]])

In [32]:
#2D arryas(matrix)
climate_data.shape

(4, 3)

In [33]:
weights

array([0.3, 0.2, 0.5])

In [34]:
weights.shape

(3,)

In [35]:
arr3 = np.array ([
    [[11,23,34],
    [13,14,15]],
                
   [[45,34,21],
    [16,73,19.5]]])

In [36]:
arr3.shape

(2, 2, 3)

In [37]:
weights

array([0.3, 0.2, 0.5])

In [38]:
weights.dtype

dtype('float64')

In [39]:
climate_data.dtype

dtype('int32')

In [40]:
arr3 = np.array ([
    [[11,23,34],
    [13,14,15]],
                
   [[45,34,21],
    [16,73,19.5]]])

In [41]:
arr3.dtype

dtype('float64')

In [42]:
arr3

array([[[11. , 23. , 34. ],
        [13. , 14. , 15. ]],

       [[45. , 34. , 21. ],
        [16. , 73. , 19.5]]])

In [43]:
climate_data

array([[ 78,  56,  45],
       [ 90,  88,  65],
       [ 87, 145,  23],
       [110,  43,  56]])

In [44]:
np.matmul(climate_data,weights)

array([57.1, 77.1, 66.6, 69.6])

In [45]:
climate_data @ weights

array([57.1, 77.1, 66.6, 69.6])

## Working with CSV data files
Numpy aklso provide helper function reading from & writting file

In [46]:
climate_data

array([[ 78,  56,  45],
       [ 90,  88,  65],
       [ 87, 145,  23],
       [110,  43,  56]])

In [47]:
climate_data.shape

(4, 3)

In [48]:
weight = np.array([0.3,0.4,0.2])

In [49]:
yields =climate_data @ weights

In [50]:
yields

array([57.1, 77.1, 66.6, 69.6])

In [51]:
yields.shape

(4,)

In [52]:
climate_results = np.concatenate((climate_data,yields.reshape(4,1)),axis=1)

In [53]:
climate_results

array([[ 78. ,  56. ,  45. ,  57.1],
       [ 90. ,  88. ,  65. ,  77.1],
       [ 87. , 145. ,  23. ,  66.6],
       [110. ,  43. ,  56. ,  69.6]])

In [54]:
np.savetxt('climate_results.txt',
          climate_results,fmt ='%.2f',
          header = 'temperature,rainfall,humidity,yeild_apples,',
          comments = '')

## Other ways of  creating Numpy arrays

In [55]:
#All Zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
#all ones
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
#Random vector
np.random.rand(5)

array([0.56638309, 0.27113083, 0.73171386, 0.54946561, 0.46112304])

In [58]:
#Random matrix
np.random.rand(2,3)

array([[0.61548524, 0.77919191, 0.53166059],
       [0.26415867, 0.39882949, 0.17172092]])

In [59]:
#fixed value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [60]:
#Range with start end and step
np.arange(10,90,3).shape

(27,)

In [61]:
# Equal space number is range
np.linspace(3,23,9)

array([ 3. ,  5.5,  8. , 10.5, 13. , 15.5, 18. , 20.5, 23. ])

In [62]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])